const constants = { alignContent:
  { stretch: 'stretch',
    center: 'center',
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    spaceBetween: 'space-between',
    spaceAround: 'space-around',
    initial: 'initial',
    inherit: 'inherit' },
 alignItems:
  { stretch: 'stretch',
    center: 'center',
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    baseline: 'baseline',
    initial: 'initial',
    inherit: 'inherit' },
 alignSelf:
  { auto: 'auto',
    stretch: 'stretch',
    center: 'center',
    flexStart: 'flex-start',
    flexEnd: 'flex-end',
    baseline: 'baseline',
    initial: 'initial',
    inherit: 'inherit' },
 animation: { initial: 'initial', inherit: 'inherit' },
 animationDelay: { initial: 'initial', inherit: 'inherit' },
 animationDirection:
  { normal: 'normal',
    reverse: 'reverse',
    alternate: 'alternate',
    alternateReverse: 'alternate-reverse',
    initial: 'initial',
    inherit: 'inherit' },
 animationDuration: { initial: 'initial', inherit: 'inherit' },
 animationFillMode:
  { none: 'none',
    forwards: 'forwards',
    backwards: 'backwards',
    both: 'both',
    initial: 'initial',
    inherit: 'inherit' },
 animationIterationCount: { infinite: 'infinite', initial: 'initial', inherit: 'inherit' },
 animationName: { none: 'none', initial: 'initial', inherit: 'inherit' },
 animationPlayState:
  { paused: 'paused',
    running: 'running',
    initial: 'initial',
    inherit: 'inherit' },
 backfaceVisibility:
  { visible: 'visible',
    hidden: 'hidden',
    initial: 'initial',
    inherit: 'inherit' },
 background: { initial: 'initial', inherit: 'inherit' },
 backgroundAttachment:
  { scroll: 'scroll',
    fixed: 'fixed',
    local: 'local',
    initial: 'initial',
    inherit: 'inherit' },
 backgroundClip:
  { borderBox: 'border-box',
    paddingBox: 'padding-box',
    contentBox: 'content-box',
    initial: 'initial',
    inherit: 'inherit' },
 backgroundColor:
  { transparent: 'transparent',
    initial: 'initial',
    inherit: 'inherit' },
 backgroundImage: { none: 'none', initial: 'initial', inherit: 'inherit' },
 backgroundOrigin:
  { paddingBox: 'padding-box',
    borderBox: 'border-box',
    contentBox: 'content-box',
    initial: 'initial',
    inherit: 'inherit' },
 backgroundPosition: { initial: 'initial', inherit: 'inherit' },
 backgroundRepeat:
  { repeat: 'repeat',
    repeatX: 'repeat-x',
    repeatY: 'repeat-y',
    noRepeat: 'no-repeat',
    initial: 'initial',
    inherit: 'inherit' },
 backgroundSize: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 border: { initial: 'initial', inherit: 'inherit' },
 borderBottom: { initial: 'initial', inherit: 'inherit' },
 borderBottomColor:
  { transparent: 'transparent',
    initial: 'initial',
    inherit: 'inherit' },
 borderBottomLeftRadius: { initial: 'initial', inherit: 'inherit' },
 borderBottomRightRadius: { initial: 'initial', inherit: 'inherit' },
 borderBottomStyle:
  { none: 'none',
    hidden: 'hidden',
    dotted: 'dotted',
    dashed: 'dashed',
    solid: 'solid',
    double: 'double',
    groove: 'groove',
    ridge: 'ridge',
    inset: 'inset',
    outset: 'outset',
    initial: 'initial',
    inherit: 'inherit' },
 borderBottomWidth:
  { medium: 'medium',
    thin: 'thin',
    thick: 'thick',
    initial: 'initial',
    inherit: 'inherit' },
 borderCollapse:
  { separate: 'separate',
    collapse: 'collapse',
    initial: 'initial',
    inherit: 'inherit' },
 borderColor:
  { transparent: 'transparent',
    initial: 'initial',
    inherit: 'inherit' },
 borderImage: { initial: 'initial', inherit: 'inherit' },
 borderImageOutset: { initial: 'initial', inherit: 'inherit' },
 borderImageRepeat: { space: 'space', initial: 'initial', inherit: 'inherit' },
 borderImageSlice: { initial: 'initial', inherit: 'inherit' },
 borderImageSource: { initial: 'initial', inherit: 'inherit' },
 borderImageWidth: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 borderLeft: { initial: 'initial', inherit: 'inherit' },
 borderLeftColor:
  { transparent: 'transparent',
    initial: 'initial',
    inherit: 'inherit' },
 borderLeftStyle:
  { none: 'none',
    hidden: 'hidden',
    dotted: 'dotted',
    dashed: 'dashed',
    solid: 'solid',
    double: 'double',
    groove: 'groove',
    ridge: 'ridge',
    inset: 'inset',
    outset: 'outset',
    initial: 'initial',
    inherit: 'inherit' },
 borderLeftWidth:
  { medium: 'medium',
    thin: 'thin',
    thick: 'thick',
    initial: 'initial',
    inherit: 'inherit' },
 borderRadius: { initial: 'initial', inherit: 'inherit' },
 borderRight: { initial: 'initial', inherit: 'inherit' },
 borderRightColor:
  { transparent: 'transparent',
    initial: 'initial',
    inherit: 'inherit' },
 borderRightStyle:
  { none: 'none',
    hidden: 'hidden',
    dotted: 'dotted',
    dashed: 'dashed',
    solid: 'solid',
    double: 'double',
    groove: 'groove',
    ridge: 'ridge',
    inset: 'inset',
    outset: 'outset',
    initial: 'initial',
    inherit: 'inherit' },
 borderRightWidth:
  { medium: 'medium',
    thin: 'thin',
    thick: 'thick',
    initial: 'initial',
    inherit: 'inherit' },
 borderSpacing: { initial: 'initial', inherit: 'inherit' },
 borderStyle:
  { none: 'none',
    hidden: 'hidden',
    dotted: 'dotted',
    dashed: 'dashed',
    solid: 'solid',
    double: 'double',
    groove: 'groove',
    ridge: 'ridge',
    inset: 'inset',
    outset: 'outset',
    initial: 'initial',
    inherit: 'inherit' },
 borderTop: { initial: 'initial', inherit: 'inherit' },
 borderTopColor:
  { transparent: 'transparent',
    initial: 'initial',
    inherit: 'inherit' },
 borderTopLeftRadius: { initial: 'initial', inherit: 'inherit' },
 borderTopRightRadius: { initial: 'initial', inherit: 'inherit' },
 borderTopStyle:
  { none: 'none',
    hidden: 'hidden',
    dotted: 'dotted',
    dashed: 'dashed',
    solid: 'solid',
    double: 'double',
    groove: 'groove',
    ridge: 'ridge',
    inset: 'inset',
    outset: 'outset',
    initial: 'initial',
    inherit: 'inherit' },
 borderTopWidth:
  { medium: 'medium',
    thin: 'thin',
    thick: 'thick',
    initial: 'initial',
    inherit: 'inherit' },
 borderWidth:
  { medium: 'medium',
    thin: 'thin',
    thick: 'thick',
    initial: 'initial',
    inherit: 'inherit' },
 bottom: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 boxShadow:
  { none: 'none',
    inset: 'inset',
    initial: 'initial',
    inherit: 'inherit' },
 boxSizing: { 
    initial: 'initial',
    inherit: 'inherit',
    borderBox: 'border-box',
    contentBox: 'content-box'
  },
 captionSide:
  { top: 'top',
    bottom: 'bottom',
    initial: 'initial',
    inherit: 'inherit' },
 clear:
  { none: 'none',
    left: 'left',
    right: 'right',
    both: 'both',
    initial: 'initial',
    inherit: 'inherit' },
 clip: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 color: { initial: 'initial', inherit: 'inherit' },
 columnCount: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 columnFill:
  { balance: 'balance',
    auto: 'auto',
    initial: 'initial',
    inherit: 'inherit' },
 columnGap: { normal: 'normal', initial: 'initial', inherit: 'inherit' },
 columnRule: { initial: 'initial', inherit: 'inherit' },
 columnRuleColor: { initial: 'initial', inherit: 'inherit' },
 columnRuleStyle: { initial: 'initial', inherit: 'inherit' },
 columnRuleWidth: { initial: 'initial', inherit: 'inherit' },
 columnSpan: { '1': '1', all: 'all', initial: 'initial', inherit: 'inherit' },
 columnWidth: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 columns: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 content:
  { normal: 'normal',
    none: 'none',
    counter: 'counter',
    openQuote: 'open-quote',
    closeQuote: 'close-quote',
    noOpenQuote: 'no-open-quote',
    noCloseQuote: 'no-close-quote',
    initial: 'initial',
    inherit: 'inherit' },
 counterIncrement: { none: 'none', initial: 'initial', inherit: 'inherit' },
 counterReset: { none: 'none', initial: 'initial', inherit: 'inherit' },
 cursor:
  { alias: 'alias',
    allScroll: 'all-scroll',
    auto: 'auto',
    cell: 'cell',
    contextMenu: 'context-menu',
    colResize: 'col-resize',
    copy: 'copy',
    crosshair: 'crosshair',
    default: 'default',
    eResize: 'e-resize',
    ewResize: 'ew-resize',
    grab: 'grab',
    grabbing: 'grabbing',
    help: 'help',
    move: 'move',
    nResize: 'n-resize',
    neResize: 'ne-resize',
    neswResize: 'nesw-resize',
    nsResize: 'ns-resize',
    nwResize: 'nw-resize',
    nwseResize: 'nwse-resize',
    noDrop: 'no-drop',
    none: 'none',
    notAllowed: 'not-allowed',
    pointer: 'pointer',
    progress: 'progress',
    rowResize: 'row-resize',
    sResize: 's-resize',
    seResize: 'se-resize',
    swResize: 'sw-resize',
    text: 'text',
    verticalText: 'vertical-text',
    wResize: 'w-resize',
    wait: 'wait',
    zoomIn: 'zoom-in',
    zoomOut: 'zoom-out',
    initial: 'initial',
    inherit: 'inherit' },
 direction: { ltr: 'ltr', rtl: 'rtl', initial: 'initial', inherit: 'inherit' },
 display:
  { inline: 'inline',
    block: 'block',
    flex: 'flex',
    inlineBlock: 'inline-block',
    inlineFlex: 'inline-flex',
    inlineTable: 'inline-table',
    listItem: 'list-item',
    runIn: 'run-in',
    table: 'table',
    tableCaption: 'table-caption',
    tableHeaderGroup: 'table-header-group',
    tableFooterGroup: 'table-footer-group',
    tableRowGroup: 'table-row-group',
    tableCell: 'table-cell',
    tableColumn: 'table-column',
    tableRow: 'table-row',
    none: 'none',
    initial: 'initial',
    inherit: 'inherit' },
 emptyCells:
  { show: 'show',
    hide: 'hide',
    initial: 'initial',
    inherit: 'inherit' },
 flex:
  { auto: 'auto',
    initial: 'initial',
    none: 'none',
    inherit: 'inherit' },
 flexBasis: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 flexDirection:
  { row: 'row',
    rowReverse: 'row-reverse',
    column: 'column',
    columnReverse: 'column-reverse',
    initial: 'initial',
    inherit: 'inherit' },
 flexFlow: { initial: 'initial', inherit: 'inherit' },
 flexGrow: { initial: 'initial', inherit: 'inherit' },
 flexShrink: { initial: 'initial', inherit: 'inherit' },
 flexWrap:
  { nowrap: 'nowrap',
    wrap: 'wrap',
    wrapReverse: 'wrap-reverse',
    initial: 'initial',
    inherit: 'inherit' },
 float:
  { none: 'none',
    left: 'left',
    right: 'right',
    initial: 'initial',
    inherit: 'inherit' },
 font:
  { caption: 'caption',
    icon: 'icon',
    menu: 'menu',
    messageBox: 'message-box',
    smallCaption: 'small-caption',
    statusBar: 'status-bar',
    initial: 'initial',
    inherit: 'inherit' },
 fontFamily: { initial: 'initial', inherit: 'inherit' },
 fontSize:
  { medium: 'medium',
    xxSmall: 'xx-small',
    xSmall: 'x-small',
    small: 'small',
    large: 'large',
    xLarge: 'x-large',
    xxLarge: 'xx-large',
    smaller: 'smaller',
    larger: 'larger',
    initial: 'initial',
    inherit: 'inherit' },
 fontSizeAdjust: { none: 'none', initial: 'initial', inherit: 'inherit' },
 fontStretch:
  { ultraCondensed: 'ultra-condensed',
    extraCondensed: 'extra-condensed',
    condensed: 'condensed',
    semiCondensed: 'semi-condensed',
    normal: 'normal',
    semiExpanded: 'semi-expanded',
    expanded: 'expanded',
    extraExpanded: 'extra-expanded',
    ultraExpanded: 'ultra-expanded',
    initial: 'initial',
    inherit: 'inherit' },
 fontStyle:
  { normal: 'normal',
    italic: 'italic',
    oblique: 'oblique',
    initial: 'initial',
    inherit: 'inherit' },
 fontVariant:
  { normal: 'normal',
    smallCaps: 'small-caps',
    initial: 'initial',
    inherit: 'inherit' },
 fontWeight:
  { normal: 'normal',
    bold: 'bold',
    bolder: 'bolder',
    lighter: 'lighter',
    initial: 'initial',
    inherit: 'inherit' },
 hangingPunctuation:
  { none: 'none',
    first: 'first',
    last: 'last',
    allowEnd: 'allow-end',
    forceEnd: 'force-end',
    initial: 'initial',
    inherit: 'inherit' },
 height: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 justifyContent:
  { flexStart: 'flex-start',
    flexEnd: 'flex-end',
    center: 'center',
    spaceBetween: 'space-between',
    spaceAround: 'space-around',
    initial: 'initial',
    inherit: 'inherit' },
 left: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 letterSpacing: { normal: 'normal', initial: 'initial', inherit: 'inherit' },
 lineHeight: { normal: 'normal', initial: 'initial', inherit: 'inherit' },
 listStyle: { initial: 'initial', inherit: 'inherit' },
 listStyleImage:
  { none: 'none',
    url: 'url',
    initial: 'initial',
    inherit: 'inherit' },
 listStylePosition:
  { inside: 'inside',
    outside: 'outside',
    initial: 'initial',
    inherit: 'inherit' },
 listStyleType:
  { disc: 'disc',
    armenian: 'armenian',
    circle: 'circle',
    cjkIdeographic: 'cjk-ideographic',
    decimal: 'decimal',
    decimalLeadingZero: 'decimal-leading-zero',
    georgian: 'georgian',
    hebrew: 'hebrew',
    hiragana: 'hiragana',
    hiraganaIroha: 'hiragana-iroha',
    katakana: 'katakana',
    katakanaIroha: 'katakana-iroha',
    lowerAlpha: 'lower-alpha',
    lowerGreek: 'lower-greek',
    lowerLatin: 'lower-latin',
    lowerRoman: 'lower-roman',
    none: 'none',
    square: 'square',
    upperAlpha: 'upper-alpha',
    upperLatin: 'upper-latin',
    upperRoman: 'upper-roman',
    initial: 'initial',
    inherit: 'inherit' },
 margin: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 marginBottom: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 marginLeft: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 marginRight: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 marginTop: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 maxHeight: { none: 'none', initial: 'initial', inherit: 'inherit' },
 maxWidth: { none: 'none', initial: 'initial', inherit: 'inherit' },
 '@media': {},
 minHeight: { initial: 'initial', inherit: 'inherit' },
 minWidth: { initial: 'initial', inherit: 'inherit' },
 navDown: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 navIndex: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 navLeft: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 navRight: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 navUp: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 opacity: { initial: 'initial', inherit: 'inherit' },
 order: { initial: 'initial', inherit: 'inherit' },
 outline: { initial: 'initial', inherit: 'inherit' },
 outlineColor: { invert: 'invert', initial: 'initial', inherit: 'inherit' },
 outlineOffset: { initial: 'initial', inherit: 'inherit' },
 outlineStyle:
  { none: 'none',
    hidden: 'hidden',
    dotted: 'dotted',
    dashed: 'dashed',
    solid: 'solid',
    double: 'double',
    groove: 'groove',
    ridge: 'ridge',
    inset: 'inset',
    outset: 'outset',
    initial: 'initial',
    inherit: 'inherit' },
 outlineWidth:
  { medium: 'medium',
    thin: 'thin',
    thick: 'thick',
    initial: 'initial',
    inherit: 'inherit' },
 overflow:
  { visible: 'visible',
    hidden: 'hidden',
    scroll: 'scroll',
    auto: 'auto',
    initial: 'initial',
    inherit: 'inherit' },
 overflowX:
  { visible: 'visible',
    hidden: 'hidden',
    scroll: 'scroll',
    auto: 'auto',
    initial: 'initial',
    inherit: 'inherit' },
 overflowY:
  { visible: 'visible',
    hidden: 'hidden',
    scroll: 'scroll',
    auto: 'auto',
    initial: 'initial',
    inherit: 'inherit' },
 padding: { initial: 'initial', inherit: 'inherit' },
 paddingBottom: { initial: 'initial', inherit: 'inherit' },
 paddingLeft: { initial: 'initial', inherit: 'inherit' },
 paddingRight: { initial: 'initial', inherit: 'inherit' },
 paddingTop: { initial: 'initial', inherit: 'inherit' },
 pageBreakAfter:
  { auto: 'auto',
    always: 'always',
    avoid: 'avoid',
    left: 'left',
    right: 'right',
    initial: 'initial',
    inherit: 'inherit' },
 pageBreakBefore:
  { auto: 'auto',
    always: 'always',
    avoid: 'avoid',
    left: 'left',
    right: 'right',
    initial: 'initial',
    inherit: 'inherit' },
 pageBreakInside:
  { auto: 'auto',
    avoid: 'avoid',
    initial: 'initial',
    inherit: 'inherit' },
 perspective: { none: 'none', initial: 'initial', inherit: 'inherit' },
 perspectiveOrigin: { initial: 'initial', inherit: 'inherit' },
 position:
  { static: 'static',
    absolute: 'absolute',
    fixed: 'fixed',
    relative: 'relative',
    initial: 'initial',
    inherit: 'inherit' },
 quotes: { none: 'none', initial: 'initial', inherit: 'inherit' },
 resize: { initial: 'initial', inherit: 'inherit' },
 right: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 tabSize: { initial: 'initial', inherit: 'inherit' },
 tableLayout:
  { auto: 'auto',
    fixed: 'fixed',
    initial: 'initial',
    inherit: 'inherit' },
 textAlign:
  { left: 'left',
    right: 'right',
    center: 'center',
    justify: 'justify',
    initial: 'initial',
    inherit: 'inherit' },
 textAlignLast:
  { auto: 'auto',
    left: 'left',
    right: 'right',
    center: 'center',
    justify: 'justify',
    start: 'start',
    end: 'end',
    initial: 'initial',
    inherit: 'inherit' },
 textDecoration:
  { none: 'none',
    underline: 'underline',
    overline: 'overline',
    lineThrough: 'line-through',
    initial: 'initial',
    inherit: 'inherit' },
 textDecorationColor: { initial: 'initial', inherit: 'inherit' },
 textDecorationLine:
  { none: 'none',
    underline: 'underline',
    overline: 'overline',
    lineThrough: 'line-through',
    initial: 'initial',
    inherit: 'inherit' },
 textDecorationStyle:
  { solid: 'solid',
    double: 'double',
    dotted: 'dotted',
    dashed: 'dashed',
    wavy: 'wavy',
    initial: 'initial',
    inherit: 'inherit' },
 textIndent: { initial: 'initial', inherit: 'inherit' },
 textJustify:
  { auto: 'auto',
    interWord: 'inter-word',
    interIdeograph: 'inter-ideograph',
    interCluster: 'inter-cluster',
    distribute: 'distribute',
    kashida: 'kashida',
    trim: 'trim',
    none: 'none',
    initial: 'initial',
    inherit: 'inherit' },
 textOverflow:
  { clip: 'clip',
    ellipsis: 'ellipsis',
    initial: 'initial',
    inherit: 'inherit' },
 textShadow: { none: 'none', initial: 'initial', inherit: 'inherit' },
 textTransform:
  { none: 'none',
    capitalize: 'capitalize',
    uppercase: 'uppercase',
    lowercase: 'lowercase',
    initial: 'initial',
    inherit: 'inherit' },
 top: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 transform: { none: 'none', initial: 'initial', inherit: 'inherit' },
 transformOrigin: { initial: 'initial', inherit: 'inherit' },
 transformStyle:
  { flat: 'flat',
    'preserve-3d': 'preserve-3d',
    initial: 'initial',
    inherit: 'inherit' },
 transition: { initial: 'initial', inherit: 'inherit' },
 transitionDelay: { initial: 'initial', inherit: 'inherit' },
 transitionDuration: { initial: 'initial', inherit: 'inherit' },
 transitionProperty:
  { none: 'none',
    all: 'all',
    initial: 'initial',
    inherit: 'inherit' },
 transitionTimingFunction:
  { ease: 'ease',
    linear: 'linear',
    easeIn: 'ease-in',
    easeOut: 'ease-out',
    easeInOut: 'ease-in-out',
    initial: 'initial',
    inherit: 'inherit' },
 unicodeBidi:
  { normal: 'normal',
    embed: 'embed',
    bidiOverride: 'bidi-override',
    initial: 'initial',
    inherit: 'inherit' },
 verticalAlign:
  { baseline: 'baseline',
    sub: 'sub',
    super: 'super',
    top: 'top',
    textTop: 'text-top',
    middle: 'middle',
    bottom: 'bottom',
    textBottom: 'text-bottom',
    initial: 'initial',
    inherit: 'inherit' },
 visibility:
  { visible: 'visible',
    hidden: 'hidden',
    collapse: 'collapse',
    initial: 'initial',
    inherit: 'inherit' },
 whiteSpace:
  { normal: 'normal',
    nowrap: 'nowrap',
    pre: 'pre',
    preLine: 'pre-line',
    preWrap: 'pre-wrap',
    initial: 'initial',
    inherit: 'inherit' },
 width: { auto: 'auto', initial: 'initial', inherit: 'inherit' },
 wordBreak:
  { normal: 'normal',
    breakAll: 'break-all',
    initial: 'initial',
    inherit: 'inherit' },
 wordSpacing: { normal: 'normal', initial: 'initial', inherit: 'inherit' },
 wordWrap:
  { normal: 'normal',
    breakWord: 'break-word',
    initial: 'initial',
    inherit: 'inherit' },
 zIndex: { auto: 'auto', initial: 'initial', inherit: 'inherit' } };

module.exports = constants;
